# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Image(object):
    def setupUi(self, Image):
        Image.setObjectName("Image")
        Image.resize(1128, 888)
        self.centralwidget = QtWidgets.QWidget(Image)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(60, 0, 1024, 720))
        self.image.setMaximumSize(QtCore.QSize(1920, 1080))
        self.image.setTextFormat(QtCore.Qt.PlainText)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setWordWrap(True)
        self.image.setObjectName("image")
        Image.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Image)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Image.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Image)
        self.statusbar.setObjectName("statusbar")
        Image.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(Image)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(Image)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Image)
        QtCore.QMetaObject.connectSlotsByName(Image)

    def retranslateUi(self, Image):
        _translate = QtCore.QCoreApplication.translate
        Image.setWindowTitle(_translate("Image", "MainWindow"))
        self.image.setText(_translate("Image", "To Upload Image File -> Load"))
        self.menuFile.setTitle(_translate("Image", "File"))
        self.actionLoad.setText(_translate("Image", "Load"))
        self.actionSave.setText(_translate("Image", "Save As"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Image = QtWidgets.QMainWindow()
    ui = Ui_Image()
    ui.setupUi(Image)
    Image.show()
    sys.exit(app.exec_())
